# Generated by Django 4.1.4 on 2022-12-13 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccumulatingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASNoStamps', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Clerk',
            fields=[
                ('ClNo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ClName', models.CharField(max_length=100)),
                ('ClAddress', models.CharField(max_length=100)),
                ('ClPhoneNo', models.CharField(max_length=11)),
                ('ClWorkShift', models.IntegerField()),
                ('ClSalary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CPhoneNo', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('CName', models.CharField(max_length=100)),
                ('CAddress', models.CharField(max_length=100)),
                ('CPoint', models.IntegerField()),
                ('CDeductionDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DiscountService',
            fields=[
                ('DSTier', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('DSRate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('MNo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('MName', models.CharField(max_length=100)),
                ('MAddress', models.CharField(max_length=100)),
                ('MPhoneNo', models.CharField(max_length=11)),
                ('MSalary', models.IntegerField()),
                ('MBonus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('PBarcode', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('PName', models.CharField(max_length=100)),
                ('PQty', models.IntegerField()),
                ('PPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RestockingBill',
            fields=[
                ('RBNo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('RBDate', models.DateTimeField()),
                ('RBPrice', models.IntegerField()),
                ('MNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.manager')),
            ],
        ),
        migrations.CreateModel(
            name='SellingBill',
            fields=[
                ('SBNo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('SBDate', models.DateTimeField()),
                ('SBPrice', models.IntegerField()),
                ('CNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('ClNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clerk')),
            ],
        ),
        migrations.CreateModel(
            name='WholesaleCompany',
            fields=[
                ('WCName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('WCAddress', models.CharField(max_length=100)),
                ('WCPhoneNo', models.CharField(max_length=11)),
                ('PBarcode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='SellingBillDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SBQty', models.IntegerField()),
                ('PBarcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('SBNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sellingbill')),
            ],
        ),
        migrations.AddField(
            model_name='sellingbill',
            name='products',
            field=models.ManyToManyField(through='core.SellingBillDetail', to='core.product'),
        ),
        migrations.CreateModel(
            name='RestockingBillDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RBWPrice', models.IntegerField()),
                ('RBQty', models.IntegerField()),
                ('PBarcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('RBNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restockingbill')),
            ],
        ),
        migrations.AddField(
            model_name='restockingbill',
            name='WCName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wholesalecompany'),
        ),
        migrations.AddField(
            model_name='restockingbill',
            name='products',
            field=models.ManyToManyField(through='core.RestockingBillDetail', to='core.product'),
        ),
        migrations.AddField(
            model_name='customer',
            name='c_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.discountservice'),
        ),
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(through='core.AccumulatingService', to='core.product'),
        ),
        migrations.AddField(
            model_name='accumulatingservice',
            name='CPhoneNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer'),
        ),
        migrations.AddField(
            model_name='accumulatingservice',
            name='PBarcode',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
