# Generated by Django 4.1.4 on 2022-12-13 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='c_tier',
            new_name='CTier',
        ),
    ]
