# Generated by Django 4.1.4 on 2022-12-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_pdiscountrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellingbill',
            old_name='CNo',
            new_name='CPhoneNo',
        ),
    ]
