# Generated by Django 4.1.4 on 2022-12-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_cno_sellingbill_cphoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='accumulatingservice',
            name='ASMinStamps',
            field=models.IntegerField(default=1),
        ),
    ]
