# Generated by Django 4.1.4 on 2022-12-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_accumulatingservice_asminstamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountservice',
            name='DSMaxPoint',
            field=models.IntegerField(default=1),
        ),
    ]
