# Generated by Django 4.1.4 on 2022-12-15 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_discountservice_dsmaxpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesalecompany',
            name='PBarcode',
        ),
        migrations.AddField(
            model_name='product',
            name='WCName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.wholesalecompany'),
        ),
    ]
